services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rwalet
    ports:
      - 5432:5432
  frontend:
    build:
      context: client/.
    ports:
      - "4200:4200"
    depends_on:
      - backend
  backend:
    build:
      context: server/.
    ports:
      - "3000:3000"
    depends_on:
      - db
